### ISSUE TITLE
Dry::Struct::Constructor does not respond to `#optional?`

### ISSUE THREAD

**Issue by ianks** [dry-rb/dry-struct#133]
**Describe the bug**

When upgrading from dry-types 1.1 to 1.2, we started getting a new error:

```
#<NoMethodError: undefined method `optional?' for #<Dry::Struct::Constructor type=Shopify::Types::PriceSetValue>>
```

This bug occurs when `rom-core` attempts to build the type from its schema dsl. Here is the backtrace:

```
     # /home/ianks/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rom-core-5.1.2/lib/rom/schema/dsl.rb:148:in `build_type'
     # /home/ianks/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rom-core-5.1.2/lib/rom/schema/dsl.rb:132:in `build_attribute_info'
     # /home/ianks/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rom-core-5.1.2/lib/rom/schema/dsl.rb:84:in `attribute'
```
**To Reproduce**

Use a `Dry::Struct::Constructor` in a ROM schema:

```ruby
class Orders < ROM::Relation[:http]
  module Types
    class PriceSetValue < Dry::Struct
      attribute :presentment_money, MoneyBag.meta[:read]
      attribute :shop_money, MoneyBag.meta[:read]
    end

    # Represents a Shopify price set
    PriceSet ||= ::Types::Constructor(PriceSetValue)
  end

  schema(:orders, infer: false) do
    attribute :total_tax_set, Types::PriceSet
  end
end
```

**Expected behavior**

`Dry::Struct::Constructor` to respond to `#optional?`

**Comment by solnic** [comment]
Struct's `Constructor` does not delegate to the underlying type like in dry-types, so maybe there was a change in rom-core that causes this issue, but it doesn't matter to be honest because the main bug is that constructor here does not behave like the standard constructor from dry-types, where method_missing [delegates to the wrapped type](https://github.com/dry-rb/dry-types/blob/master/lib/dry/types/constructor.rb#L156-L168). We should have a common abstraction for this behavior to avoid duplication.

**Comment by flash-gordon** [comment]
@ianks with dry-types 1.2.2 this won't be an issue for you. Now `Types::Constructor` returns the struct class back, that was the actual problem, not lack of `optional?` for `Struct::Constructor`

**Comment by flash-gordon** [comment]
fixed in #147
